const columns = [
    {name: "ID", dataKey: "id", sortable: true},
    {name: "DATE", dataKey: "date", sortable: true},
    {name: "TIME", dataKey: "time", sortable: true},
    {name: "TRANSACTION NO.", dataKey: "transaction_no", sortable: true},
    {name: "ITEM NO", dataKey: "item_no"},
    {name: "ITEM NAME", dataKey: "item_name"},
    {name: "UNIT COST", dataKey: "unit_cost", sortable: true},
    {name: "QUANTITY", dataKey: "quantity", sortable: true},
    {name: "AMOUNT", dataKey: "amount", sortable: true},
    {name: "DISCOUNT", dataKey: "discount", sortable: true},
    {name: "TOTAL", dataKey: "total", sortable: true},
    {name: "CUSTOMER TYPE", dataKey: "customer_type", sortable: true},
    {name: "CUSTOMER NAME", dataKey: "customer_name", sortable: true},
    {name: "PAYMENT METHOD", dataKey: "payment_method", sortable: true},
    {name: "SALES PERSON", dataKey: "sales_person", sortable: true},
    {name: "REMARKS", dataKey: "remarks", sortable: true},
  ];
  
  const itemOptions = [
    {name: "Tarpaulin", dataKey: "tarpaulin"},
    {name: "Photocopy", dataKey: "photocopy"},
    {name: "Photo print", dataKey: "photo print"},
    {name: "others", dataKey: "others"},
  ];
  
  const typeOptions = [
    {name: "Walk in", dataKey: "walk in"},
    {name: "Online", dataKey: "online"},
  ];
  
  const transactions = [
    {
      id: 1,
      date: '10/15/2014',
      time: '08: 00 am',
      transaction_no: "0001",
      item_no: '0000',
      item_name: 'Tarpaulin',
      unit_cost: '640',
      quantity: '1',
      amount: '640',
      discount: '0',
      total: '640',
      customer_type: 'Walk in',
      customer_name: 'Hansam',
      payment_method: 'Cash',
      sales_person: 'Christian',
      remarks: '',
    },
    {
      id: 1,
      date: '10/15/2014',
      time: '08: 00 am',
      transaction_no: "0002",
      item_no: '0000',
      item_name: 'Photo print',
      unit_cost: '640',
      quantity: '1',
      amount: '640',
      discount: '0',
      total: '640',
      customer_type: 'Online',
      customer_name: 'Hansam',
      payment_method: 'Cash',
      sales_person: 'Christian',
      remarks: '',
    },
    {
      id: 1,
      date: '10/15/2014',
      time: '08: 00 am',
      transaction_no: "0003",
      item_no: '0000',
      item_name: 'Others',
      unit_cost: '640',
      quantity: '1',
      amount: '640',
      discount: '0',
      total: '640',
      customer_type: 'Online',
      customer_name: 'Hansam',
      payment_method: 'Cash',
      sales_person: 'Christian',
      remarks: '',
    },
    {
      id: 1,
      date: '10/15/2014',
      time: '08: 00 am',
      transaction_no: "0004",
      item_no: '0000',
      item_name: 'Photocopy',
      unit_cost: '640',
      quantity: '1',
      amount: '640',
      discount: '0',
      total: '640',
      customer_type: 'Online',
      customer_name: 'Hansam',
      payment_method: 'Cash',
      sales_person: 'Christian',
      remarks: '',
    },
  ];
  
  export {columns, transactions, itemOptions, typeOptions};