const columns = [

    {name: "ID", dataKey: "id", sortable: true},
    {name: "DATE", dataKey: "date", sortable: true},
    {name: "TIME", dataKey: "time", sortable: true},
    {name: "TRANSACTION NO.", dataKey: "transaction_no", sortable: true},
    {name: "ITEM NO", dataKey: "item_no"},
    {name: "ITEM NAME", dataKey: "item_name"},
    {name: "UNIT COST", dataKey: "unit_cost", sortable: true},
    {name: "QUANTITY", dataKey: "quantity", sortable: true},
    {name: "AMOUNT", dataKey: "amount", sortable: true},
    {name: "DISCOUNT", dataKey: "discount", sortable: true},
    {name: "TOTAL", dataKey: "total", sortable: true},
    {name: "CUSTOMER TYPE", dataKey: "customer_type", sortable: true},
    {name: "CUSTOMER NAME", dataKey: "customer_name", sortable: true},
    {name: "PAYMENT METHOD", dataKey: "payment_type", sortable: true},
    {name: "SALES PERSON", dataKey: "sales_person", sortable: true},
    {name: "REMARKS", dataKey: "remarks", sortable: true},
  ];
  
  const statusOptions = [
    {name: "Tarpulin", dataKey: "tarpulin"},
    {name: "Photo Copy", dataKey: "photo_copy"},
    {name: "T-shirt Printing", dataKey: "tshirt"},
  ];
  
  const users = [
   {
    id:1,
    date:'12/09/21',
    time: '12:24',
    transaction_no: 9,
    item_no:9,
    item_name:'Tarpulin',
    unit_cost: 7,
    quantity: 9,
    amount: 88,
    discount: 8,
    total:89,
    customer_type: 'huhuh',
    customer_name:'jijij',
    payment_type:'Gcash',
    sales_person:'Roland Choi',
    remarks:'Dakog pAg Utang'
   },
   {
    id:1,
    date:'12/09/21',
    time: '12:24',
    transaction_no: 9,
    item_no:9,
    item_name:'Tarpulin',
    unit_cost: 7,
    quantity: 9,
    amount: 88,
    discount: 8,
    total:89,
    customer_type: 'huhuh',
    customer_name:'jijij',
    payment_type:'Gcash',
    sales_person:'Roland Choi',
    remarks:'Dakog pAg Utang'
   },
   {
    id:1,
    date:'12/09/21',
    time: '12:24',
    transaction_no: 9,
    item_no:9,
    item_name:'photoCopy',
    unit_cost: 7,
    quantity: 9,
    amount: 88,
    discount: 8,
    total:89,
    customer_type: 'huhuh',
    customer_name:'jijij',
    payment_type:'Gcash',
    sales_person:'Roland Choi',
    remarks:'Dakog pAg Utang'
   },
   {
    id:1,
    date:'12/09/21',
    time: '12:24',
    transaction_no: 9,
    item_no:9,
    item_name:'Tarpulin',
    unit_cost: 7,
    quantity: 9,
    amount: 88,
    discount: 8,
    total:89,
    customer_type: 'huhuh',
    customer_name:'hansam',
    payment_type:'Gcash',
    sales_person:'Roland Choi',
    remarks:'Dakog pAg Utang'
   },
   {
    id:1,
    date:'12/09/21',
    time: '12:24',
    transaction_no: 9,
    item_no:9,
    item_name:'Tarpulin',
    unit_cost: 7,
    quantity: 9,
    amount: 88,
    discount: 8,
    total:89,
    customer_type: 'huhuh',
    customer_name:'hansam',
    payment_type:'Gcash',
    sales_person:'Roland Choi',
    remarks:'Dakog pAg Utang'
   },
   {
    id:1,
    date:'12/09/21',
    time: '12:24',
    transaction_no: 9,
    item_no:9,
    item_name:'Tarpulin',
    unit_cost: 7,
    quantity: 9,
    amount: 88,
    discount: 8,
    total:89,
    customer_type: 'huhuh',
    customer_name:'hansam',
    payment_type:'Gcash',
    sales_person:'Roland Choi',
    remarks:'Dakog pAg Utang'
   },

  ];
  
  export {columns, users, statusOptions};