const columns = [
  { uid: "date", name: "Date", sortable: true },
  { uid: "time", name: "Time", sortable: true },
  { uid: "transaction_no", name: "Transaction No", sortable: true },
  { uid: "item_no", name: "Item No", sortable: true },
  { uid: "item_name", name: "Item Name", sortable: true },
  { uid: "unit_cost", name: "Unit Cost", sortable: true },
  { uid: "quantity", name: "Quantity", sortable: true },
  { uid: "amount", name: "Amount", sortable: true },
  { uid: "discount", name: "Discount", sortable: true },
  { uid: "total", name: "Total", sortable: true },
  { uid: "customer_type", name: "Customer Type", sortable: true },
  { uid: "customer_name", name: "Customer Name", sortable: true },
  { uid: "payment_method", name: "Payment Method", sortable: true },
  { uid: "sales_person", name: "Sales Person", sortable: true },
  { uid: "remarks", name: "Remarks", sortable: true },
  { uid: "actions", name: "Actions", sortable: false },
];

const statusOptions = [
  { name: "Active", uid: "active" },
  { name: "Paused", uid: "paused" },
  { name: "Vacation", uid: "vacation" },
];

const users = [
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Roland',
    payment_method: 'Cash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Roland',
    payment_method: 'Cash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Roland',
    payment_method: 'Cash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Hansam',
    payment_method: 'Gcash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Hansam',
    payment_method: 'Gcash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Hansam',
    payment_method: 'Gcash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Hansam',
    payment_method: 'Gcash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Hansam',
    payment_method: 'Cash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Hansam',
    payment_method: 'Cash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Hansam',
    payment_method: 'Cash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Hansam',
    payment_method: 'Cash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Hansam',
    payment_method: 'Cash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: "10/13/24",
    transaction: "1",
    item: "Tarpulin",
    quantity: "1",
    discount: '00.00',

    unitcost: "00.00",
    total: "00.00",
    costumertype: "Walkin",
    costumername: "Roland Clarion",
    paymentmetod: "Gcash",
    remark: "blabla",
  },

];
const transactions = [
  { key: "tarpulin", label: "Tarpulin" },
  { key: "printing p-shirt", label: "Printing T-shirt" },
  { key: "paper print", label: "Paper Print" },

];
const costumer_types = [
  { key: 'Walkin', label: 'Walk-in' },
  { key: 'Online', label: 'Online' }
]
export { columns, users, statusOptions, transactions, costumer_types };
