const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "DATE", uid: "date", sortable: true},
  {name: "TIME", uid: "time", sortable: true},
  {name: "TRANSACTION NO.", uid: "transaction_no", sortable: true},
  {name: "ITEM NO", uid: "item_no"},
  {name: "ITEM NAME", uid: "item_name"},
  {name: "UNIT COST", uid: "unit_cost", sortable: true},
  {name: "QUANTITY", uid: "quantity", sortable: true},
  {name: "AMOUNT", uid: "amount", sortable: true},
  {name: "DISCOUNT", uid: "discount", sortable: true},
  {name: "TOTAL", uid: "total", sortable: true},
  {name: "CUSTOMER TYPE", uid: "customer_type", sortable: true},
  {name: "CUSTOMER NAME", uid: "customer_name", sortable: true},
  {name: "PAYMENT METHOD", uid: "payment_method", sortable: true},
  {name: "SALES PERSON", uid: "sales_person", sortable: true},
  {name: "REMARKS", uid: "remarks", sortable: true},
  {name: "ACTIONS", uid: "actions"},
];

const itemOptions = [
  {name: "Tarpaulin", uid: "tarpaulin"},
  {name: "Photocopy", uid: "photocopy"},
  {name: "Photo print", uid: "photo print"},
  {name: "others", uid: "others"},
];

const typeOptions = [
  {name: "Walk in", uid: "walk in"},
  {name: "Online", uid: "online"},
];

const transactions = [
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Tarpaulin',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Walk in',
    customer_name: 'Hansam',
    payment_method: 'Cash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Photo print',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Online',
    customer_name: 'Hansam',
    payment_method: 'Cash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Others',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Online',
    customer_name: 'Hansam',
    payment_method: 'Cash',
    sales_person: 'Christian',
    remarks: '',
  },
  {
    id: 1,
    date: '10/15/2014',
    time: '08: 00 am',
    transaction_no: "0001",
    item_no: '0000',
    item_name: 'Photocopy',
    unit_cost: '640',
    quantity: '1',
    amount: '640',
    discount: '0',
    total: '640',
    customer_type: 'Online',
    customer_name: 'Hansam',
    payment_method: 'Cash',
    sales_person: 'Christian',
    remarks: '',
  },
];

export {columns, transactions, itemOptions, typeOptions};